version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: contact_db
    environment:
      POSTGRES_DB: contact_db
      POSTGRES_USER: contact_user
      POSTGRES_PASSWORD: contact_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U contact_user -d contact_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend API
  backend:
    build: ./backend
    container_name: contact_backend
    environment:
      DATABASE_URL: postgresql://contact_user:contact_password@db:5432/contact_db
      HOST: 0.0.0.0
      PORT: 8000
      ALLOWED_ORIGINS: http://localhost:5173,http://localhost:3000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend (for production)
  frontend:
    build: ./frontend
    container_name: contact_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: http://localhost:8000

volumes:
  postgres_data:
