services:
  - type: web
    name: contact-management-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: UPLOAD_DIR
        value: /tmp/uploads/
      - key: TESSERACT_PATH
        value: /usr/bin/tesseract
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: SPACY_MODEL
        value: en_core_web_sm
